# Generated by Django 4.1 on 2022-08-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='user.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
