# Generated by Django 4.1 on 2022-09-16 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_contact_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
